# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b8cf185dac3ef1acccb1bee5457b751f516ce81d5aa9ea1e7e3803885a6d6f429dcbc50a92692e041aae2907fdfa0cc5ea1448e5642de5b75ddf1092a80a1d3

test:
  secret_key_base: 24f1e72c6e8340cdf5399e2f1b6d7df23d968226b9677695487da162dfe974f0b491f674dadf98ba55357c73dd2e3f99c7efedabe75f109332492783c98ad240

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
